/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_watch_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWatchRoomError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_watch_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWatchRoomError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_watch_room_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWatchRoomByIdError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_rooms_by_host`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRoomsByHostError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_watch_room`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWatchRoomError {
    Status500(),
    UnknownValue(serde_json::Value),
}


pub async fn create_watch_room(configuration: &configuration::Configuration, new_watch_room: models::NewWatchRoom) -> Result<models::WatchRoom, Error<CreateWatchRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_new_watch_room = new_watch_room;

    let uri_str = format!("{}/watch-rooms", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_new_watch_room);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WatchRoom`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WatchRoom`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateWatchRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_watch_room(configuration: &configuration::Configuration, room_id: &str) -> Result<i32, Error<DeleteWatchRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room_id = room_id;

    let uri_str = format!("{}/watch-rooms/{room_id}", configuration.base_path, room_id=crate::apis::urlencode(p_path_room_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `i32`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `i32`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWatchRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_watch_room_by_id(configuration: &configuration::Configuration, room_id: &str) -> Result<models::WatchRoom, Error<GetWatchRoomByIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room_id = room_id;

    let uri_str = format!("{}/watch-rooms/{room_id}", configuration.base_path, room_id=crate::apis::urlencode(p_path_room_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WatchRoom`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WatchRoom`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetWatchRoomByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_rooms_by_host(configuration: &configuration::Configuration, host_user_id: &str, limit: i64, offset: i64) -> Result<Vec<models::WatchRoom>, Error<ListRoomsByHostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_host_user_id = host_user_id;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/users/{host_user_id}/watch-rooms", configuration.base_path, host_user_id=crate::apis::urlencode(p_path_host_user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("limit", &p_query_limit.to_string())]);
    req_builder = req_builder.query(&[("offset", &p_query_offset.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::WatchRoom&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::WatchRoom&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListRoomsByHostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_watch_room(configuration: &configuration::Configuration, room_id: &str, update_watch_room: models::UpdateWatchRoom) -> Result<models::WatchRoom, Error<UpdateWatchRoomError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_room_id = room_id;
    let p_body_update_watch_room = update_watch_room;

    let uri_str = format!("{}/watch-rooms/{room_id}", configuration.base_path, room_id=crate::apis::urlencode(p_path_room_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_watch_room);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WatchRoom`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WatchRoom`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateWatchRoomError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

