/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieDetail {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "duration_minutes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<Option<i32>>,
    #[serde(rename = "genres")]
    pub genres: Vec<models::Genre>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "mpaa_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpaa_rating: Option<Option<String>>,
    #[serde(rename = "people")]
    pub people: Vec<models::MovieCrewDetail>,
    #[serde(rename = "poster_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub poster_url: Option<Option<String>>,
    #[serde(rename = "release_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "reviews")]
    pub reviews: Vec<models::Review>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "video_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub video_url: Option<Option<String>>,
}

impl MovieDetail {
    pub fn new(created_at: String, genres: Vec<models::Genre>, id: uuid::Uuid, people: Vec<models::MovieCrewDetail>, reviews: Vec<models::Review>, title: String, updated_at: String) -> MovieDetail {
        MovieDetail {
            created_at,
            description: None,
            duration_minutes: None,
            genres,
            id,
            mpaa_rating: None,
            people,
            poster_url: None,
            release_date: None,
            reviews,
            title,
            updated_at,
            video_url: None,
        }
    }
}

