/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MovieCrewDetail {
    #[serde(rename = "billing_order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billing_order: Option<Option<i32>>,
    #[serde(rename = "character_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub character_name: Option<Option<String>>,
    #[serde(rename = "movie_id")]
    pub movie_id: uuid::Uuid,
    #[serde(rename = "person")]
    pub person: Box<models::Person>,
    #[serde(rename = "person_id")]
    pub person_id: uuid::Uuid,
}

impl MovieCrewDetail {
    pub fn new(movie_id: uuid::Uuid, person: models::Person, person_id: uuid::Uuid) -> MovieCrewDetail {
        MovieCrewDetail {
            billing_order: None,
            character_name: None,
            movie_id,
            person: Box::new(person),
            person_id,
        }
    }
}

