/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Movie {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "duration_minutes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<Option<i32>>,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "mpaa_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpaa_rating: Option<Option<String>>,
    #[serde(rename = "release_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Movie {
    pub fn new(created_at: String, id: i32, slug: String, title: String, updated_at: String) -> Movie {
        Movie {
            created_at,
            description: None,
            duration_minutes: None,
            id,
            mpaa_rating: None,
            release_date: None,
            slug,
            title,
            updated_at,
        }
    }
}

