/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewReview {
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "movie_id")]
    pub movie_id: i32,
    #[serde(rename = "rating")]
    pub rating: i32,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "user_name")]
    pub user_name: String,
}

impl NewReview {
    pub fn new(movie_id: i32, rating: i32, user_name: String) -> NewReview {
        NewReview {
            body: None,
            movie_id,
            rating,
            title: None,
            user_name,
        }
    }
}

