/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMovie {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "duration_minutes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<Option<i32>>,
    #[serde(rename = "mpaa_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpaa_rating: Option<Option<String>>,
    #[serde(rename = "release_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
}

impl NewMovie {
    pub fn new(slug: String, title: String) -> NewMovie {
        NewMovie {
            description: None,
            duration_minutes: None,
            mpaa_rating: None,
            release_date: None,
            slug,
            title,
        }
    }
}

