/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewPerson {
    #[serde(rename = "bio", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bio: Option<Option<String>>,
    #[serde(rename = "birth_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<Option<String>>,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
}

impl NewPerson {
    pub fn new(first_name: String, last_name: String) -> NewPerson {
        NewPerson {
            bio: None,
            birth_date: None,
            first_name,
            image_url: None,
            last_name,
            role: None,
        }
    }
}

