/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewGenre {
    #[serde(rename = "name")]
    pub name: String,
}

impl NewGenre {
    pub fn new(name: String) -> NewGenre {
        NewGenre {
            name,
        }
    }
}

