/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMovie {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "duration_minutes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_minutes: Option<Option<i32>>,
    #[serde(rename = "genre_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub genre_ids: Option<Option<Vec<uuid::Uuid>>>,
    #[serde(rename = "mpaa_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpaa_rating: Option<Option<String>>,
    #[serde(rename = "people_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub people_ids: Option<Option<Vec<models::NewMovieCrew>>>,
    #[serde(rename = "poster_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub poster_url: Option<Option<String>>,
    #[serde(rename = "release_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "video_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub video_url: Option<Option<String>>,
}

impl NewMovie {
    pub fn new(title: String) -> NewMovie {
        NewMovie {
            description: None,
            duration_minutes: None,
            genre_ids: None,
            mpaa_rating: None,
            people_ids: None,
            poster_url: None,
            release_date: None,
            title,
            video_url: None,
        }
    }
}

