/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMovieCrew {
    #[serde(rename = "billing_order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billing_order: Option<Option<i32>>,
    #[serde(rename = "person_id")]
    pub person_id: uuid::Uuid,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
}

impl NewMovieCrew {
    pub fn new(person_id: uuid::Uuid) -> NewMovieCrew {
        NewMovieCrew {
            billing_order: None,
            person_id,
            role: None,
        }
    }
}

