/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Person {
    #[serde(rename = "bio", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bio: Option<Option<String>>,
    #[serde(rename = "birth_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
}

impl Person {
    pub fn new(created_at: String, first_name: String, id: uuid::Uuid, last_name: String) -> Person {
        Person {
            bio: None,
            birth_date: None,
            created_at,
            first_name,
            id,
            image_url: None,
            last_name,
            role: None,
        }
    }
}

