/*
 * Movies API
 *
 * API documentation for my movies server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "movie_id")]
    pub movie_id: uuid::Uuid,
    #[serde(rename = "rating")]
    pub rating: i32,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "user_name")]
    pub user_name: String,
}

impl Review {
    pub fn new(created_at: String, id: uuid::Uuid, movie_id: uuid::Uuid, rating: i32, user_id: uuid::Uuid, user_name: String) -> Review {
        Review {
            body: None,
            created_at,
            id,
            movie_id,
            rating,
            title: None,
            user_id,
            user_name,
        }
    }
}

