import "./globals.css";
import {
  SidebarProvider,
} from "@/components/ui/sidebar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ModeToggle } from "@/components/ToggleTheme";
import { ThemeProvider } from "next-themes";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "10rem",
              "--sidebar-width-mobile": "20rem",
            } as React.CSSProperties
          }
        >
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ModeToggle />
              {children}
            </ThemeProvider>
          </ReactQueryProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
