"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import "./globals.css";
import {
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { RawAxiosRequestConfig } from "axios";
import { Configuration } from "@/generated";
import { ModeToggle } from "@/components/ToggleTheme";
import { ThemeProvider } from "next-themes";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export let AxiosConfig = new Configuration({
  basePath: "http://localhost:8085",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "10rem",
              "--sidebar-width-mobile": "20rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar />

          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="flex p-2 w-full">
                <SidebarTrigger/>
                <ModeToggle />
                {children}
              </main>
            </ThemeProvider>
          </ReactQueryProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
