/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchRoomParticipant {
    #[serde(rename = "is_host", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_host: Option<Option<bool>>,
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl NewWatchRoomParticipant {
    pub fn new(room_id: uuid::Uuid, user_id: uuid::Uuid) -> NewWatchRoomParticipant {
        NewWatchRoomParticipant {
            is_host: None,
            room_id,
            user_id,
        }
    }
}

