/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchRoom {
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "host_user_id")]
    pub host_user_id: uuid::Uuid,
    #[serde(rename = "invite_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invite_code: Option<Option<String>>,
    #[serde(rename = "is_private", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_private: Option<Option<bool>>,
    #[serde(rename = "room_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub room_name: Option<Option<String>>,
}

impl NewWatchRoom {
    pub fn new(content_id: uuid::Uuid, host_user_id: uuid::Uuid) -> NewWatchRoom {
        NewWatchRoom {
            content_id,
            host_user_id,
            invite_code: None,
            is_private: None,
            room_name: None,
        }
    }
}

