/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchlist {
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl NewWatchlist {
    pub fn new(content_id: uuid::Uuid, user_id: uuid::Uuid) -> NewWatchlist {
        NewWatchlist {
            content_id,
            user_id,
        }
    }
}

