/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchRoomMessage {
    #[serde(rename = "is_system_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_system_message: Option<Option<bool>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<uuid::Uuid>>,
}

impl NewWatchRoomMessage {
    pub fn new(message: String, room_id: uuid::Uuid) -> NewWatchRoomMessage {
        NewWatchRoomMessage {
            is_system_message: None,
            message,
            room_id,
            user_id: None,
        }
    }
}

