/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchRoomParticipant {
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl NewWatchRoomParticipant {
    pub fn new(is_admin: bool, room_id: uuid::Uuid, user_id: uuid::Uuid) -> NewWatchRoomParticipant {
        NewWatchRoomParticipant {
            is_admin,
            room_id,
            user_id,
        }
    }
}

