/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewWatchHistory {
    #[serde(rename = "completed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed: Option<Option<bool>>,
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "progress_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub progress_seconds: Option<Option<i32>>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl NewWatchHistory {
    pub fn new(content_id: uuid::Uuid, user_id: uuid::Uuid) -> NewWatchHistory {
        NewWatchHistory {
            completed: None,
            content_id,
            progress_seconds: None,
            user_id,
        }
    }
}

