/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWatchRoom {
    #[serde(rename = "current_time_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_time_seconds: Option<Option<i32>>,
    #[serde(rename = "is_live", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_live: Option<Option<bool>>,
}

impl UpdateWatchRoom {
    pub fn new() -> UpdateWatchRoom {
        UpdateWatchRoom {
            current_time_seconds: None,
            is_live: None,
        }
    }
}

