/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWatchHistory {
    #[serde(rename = "completed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed: Option<Option<bool>>,
    #[serde(rename = "progress_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub progress_seconds: Option<Option<i32>>,
}

impl UpdateWatchHistory {
    pub fn new() -> UpdateWatchHistory {
        UpdateWatchHistory {
            completed: None,
            progress_seconds: None,
        }
    }
}

