/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "bio", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bio: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "last_login_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_login_at: Option<Option<String>>,
    #[serde(rename = "password_hash")]
    pub password_hash: String,
    #[serde(rename = "profile_picture_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_picture_url: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl User {
    pub fn new(created_at: String, email: String, id: uuid::Uuid, password_hash: String, updated_at: String, username: String) -> User {
        User {
            bio: None,
            created_at,
            email,
            id,
            last_login_at: None,
            password_hash,
            profile_picture_url: None,
            status: None,
            updated_at,
            username,
        }
    }
}

