/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Watchlist {
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl Watchlist {
    pub fn new(content_id: uuid::Uuid, created_at: String, id: i64, user_id: uuid::Uuid) -> Watchlist {
        Watchlist {
            content_id,
            created_at,
            id,
            user_id,
        }
    }
}

