/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchHistory {
    #[serde(rename = "completed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed: Option<Option<bool>>,
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "last_watched_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_watched_at: Option<Option<String>>,
    #[serde(rename = "progress_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub progress_seconds: Option<Option<i32>>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl WatchHistory {
    pub fn new(content_id: uuid::Uuid, id: i64, user_id: uuid::Uuid) -> WatchHistory {
        WatchHistory {
            completed: None,
            content_id,
            id,
            last_watched_at: None,
            progress_seconds: None,
            user_id,
        }
    }
}

