/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchRoomParticipant {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    #[serde(rename = "joined_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub joined_at: Option<Option<String>>,
    #[serde(rename = "last_active_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_active_at: Option<Option<String>>,
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl WatchRoomParticipant {
    pub fn new(id: i64, is_admin: bool, room_id: uuid::Uuid, user_id: uuid::Uuid) -> WatchRoomParticipant {
        WatchRoomParticipant {
            id,
            is_admin,
            joined_at: None,
            last_active_at: None,
            room_id,
            user_id,
        }
    }
}

