/*
 * Users API
 *
 * API documentation for my users server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchRoom {
    #[serde(rename = "content_id")]
    pub content_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "current_time_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_time_seconds: Option<Option<i32>>,
    #[serde(rename = "host_user_id")]
    pub host_user_id: uuid::Uuid,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "invite_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invite_code: Option<Option<String>>,
    #[serde(rename = "is_live", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_live: Option<Option<bool>>,
    #[serde(rename = "is_private")]
    pub is_private: bool,
    #[serde(rename = "room_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub room_name: Option<Option<String>>,
    #[serde(rename = "updated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<String>>,
}

impl WatchRoom {
    pub fn new(content_id: uuid::Uuid, created_at: String, host_user_id: uuid::Uuid, id: uuid::Uuid, is_private: bool) -> WatchRoom {
        WatchRoom {
            content_id,
            created_at,
            current_time_seconds: None,
            host_user_id,
            id,
            invite_code: None,
            is_live: None,
            is_private,
            room_name: None,
            updated_at: None,
        }
    }
}

