/*
 * Video Server API
 *
 * API documentation for my video server.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchRoomMessage {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "is_system_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_system_message: Option<Option<bool>>,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "room_id")]
    pub room_id: uuid::Uuid,
    #[serde(rename = "sent_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<Option<String>>,
    #[serde(rename = "user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<uuid::Uuid>>,
}

impl WatchRoomMessage {
    pub fn new(id: i64, message: String, room_id: uuid::Uuid) -> WatchRoomMessage {
        WatchRoomMessage {
            id,
            is_system_message: None,
            message,
            room_id,
            sent_at: None,
            user_id: None,
        }
    }
}

